### ISSUE TITLE
babel-polyfill ?

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-bar#172]
Hi, I found a problem and I think the fix should be in cozy-bar, but let's discuss this.

### The problem

On browsers that don't support `Object.assign` (which includes IE11, which we support), some apps crash with the error `Object doesn't support property or method 'assign'`.
More specifically, this error is emitted by the cozy-bar, when it imports the `Modal` component from cozy-ui which uses [`Object.assign`](https://github.com/cozy/cozy-ui/blob/master/react/Modal/index.jsx#L167) right away.

### the solution

We really want to polyfill `Object.assign`, and in fact, we mostly do. Our apps don't have this problem. But cozy-bar doesn't polyfill it, and I really think it should.
To be clearer, cozy-bar uses the `cozy-app` babel preset, which *replaces* it's own `Object.assign` calls, but does *not* polyfill `Object.assign`. So when cozy-ui tries to use it it crashes. We're supposed to `import 'babel-polyfill'` at the very begining of the app for that.

### The alternative

Noticed that I said only *some* apps crash? A couple aren't affected, because they load the app's code (including the polyfill)  before they load `cozy-bar.js`. They tend to use [this form](https://github.com/cozy/cozy-settings/blob/master/src/index.ejs#L11) of templating.
So we could also switch all apps to this format.

___________

If we import `babel-polyfill` in `cozy-bar`, we'll essentially load it twice on each page — once in the app and once in the bar. Which makes sense because both are standalone files, but it's also annoying.

Personally I think it's better to take the weight hit, and be less fragile. Third party devs won't know they have to provide their own polyfills and might run into the same problem.

**Comment by goldoraf** [comment]
That's yet another reason to stop serving the bar by the stack, we should include it in our apps like a component.

**Comment by y-lohse** [comment]
Just a head's up, this is breaking apps in production. i'll add the polyfills to cozy-bar on monday, unless someone has a strong objection (and a better plan).

**Comment by CPatchane** [comment]
Hi @y-lohse, thanks for this issue. The problem should already be fixed in the [last version of `babel-preset-cozy-app`](https://github.com/CPatchane/create-cozy-app/blob/master/CHANGELOG.md#create-cozy-app055-cozy-scripts051-cozy-scripts-vanilla015-babel-preset-cozy-app032-eslint-config-cozy-app032-2018-02-16). I think we just need to update the dependancy in the `cozy-bar`, don't we?

**Comment by ptbrowne** [comment]
> To be clearer, cozy-bar uses the cozy-app babel preset, which replaces it's own Object.assign calls, but does not polyfill Object.assign. So when cozy-ui tries to use it it crashes.

Is it a cozy-bar issue then ? It seems that it is a cozy-ui issue because it is not shipped transpiled to npm.

**Comment by y-lohse** [comment]
> I think we just need to update the dependancy in the cozy-bar, don't we?

@CPatchane I tried it, and it doesn't seem to work. The change [set `useBuiltIns` to `false`](https://github.com/CPatchane/create-cozy-app/pull/281/files). From what I understand, setting `useBuiltIns` to `true` will transform the statement `import "babel-polyfill";` into a more fine-grained list of imports, whereas setting it to `false`just imports all of `babel-polyfill`. However, we never import `babel-polyfill` in cozy-bar, so this change has no effect.

> Is it a cozy-bar issue then ?

@ptbrowne this is a fair question. It can be:

1. A cozy-bar issue because it should provide it's own polyfills
2. A cozy-ui issue, because it should shipped transpiled / polyfilled / not use `Object.assign`
3. Issues for individual apps, because they should provide the polyfills before loading the cozy-bar

I think it's the first one.
I'm pretty sure it's not the third.
If we ship cozy-ui transpiled, can we still do `import { Thingy } from 'cozy-ui/react'`? If so, would that file be already transpiled and polyfilled ?

**Comment by y-lohse** [comment]
Since it might come up, cozy-bar.js sizes, non minified:

- Currently 610kb
- With `babel-polyfill` and `useBuiltIns false` 868kb
- With `babel-polyfill` and `useBuiltIns true` 864kb

**Comment by ptbrowne** [comment]
> If we ship cozy-ui transpiled, can we still do import { Thingy } from 'cozy-ui/react'? If so, would that file be already transpiled and polyfilled ?

Yes, and yes.

**Comment by y-lohse** [comment]
Ok, @CPatchane suggested to only add the `Object.assign` polyfill, which works like a charm and adds very little code to the cozy-bar, so I'll PR that.
Shipping cozy-ui transpiled is another subject that I think requires more discussion. I'll add an issue or a note in a trello board so we come back to it.

Thanks all!

**Comment by ptbrowne** [comment]
Thanks for the precise wrap up @y-lohse ! Don't worry, it was not that long :)

My take on this is that cozy-bar should 

* either not use Object.assign
* or use the `transform-object-assign`

What is still not clear to me is why the transform-object-assign plugin is not included by defualt via babel-preset-env.

When setting debug: true in my babelrc with env set to ie >= 11, here is the list of plugins I have:

```
  check-es2015-constants {"ie":"11"}
  transform-es2015-arrow-functions {"ie":"11"}
  transform-es2015-block-scoping {"ie":"11"}
  transform-es2015-classes {"ie":"11"}
  transform-es2015-computed-properties {"ie":"11"}
  transform-es2015-destructuring {"ie":"11"}
  transform-es2015-duplicate-keys {"ie":"11"}
  transform-es2015-for-of {"ie":"11"}
  transform-es2015-function-name {"ie":"11"}
  transform-es2015-literals {"ie":"11"}
  transform-es2015-object-super {"ie":"11"}
  transform-es2015-parameters {"ie":"11"}
  transform-es2015-shorthand-properties {"ie":"11"}
  transform-es2015-spread {"ie":"11"}
  transform-es2015-sticky-regex {"ie":"11"}
  transform-es2015-template-literals {"ie":"11"}
  transform-es2015-typeof-symbol {"ie":"11"}
  transform-es2015-unicode-regex {"ie":"11"}
  transform-regenerator {"ie":"11"}
  transform-exponentiation-operator {"ie":"11"}
  transform-async-to-generator {"ie":"11"}
  syntax-trailing-function-commas {"ie":"11"}
```

**Comment by ptbrowne** [comment]
I guess by reading : https://github.com/babel/babel/issues/7228 that it is different from other transforms since it is not a *syntax* thing but a "built-in" thing that must be polyfill. I have a bit of trouble to understand this all `built-ins : true` option :/

**Comment by y-lohse** [comment]
On using `transform-object-assign` vs the polyfill, the [doc says](https://babeljs.io/docs/plugins/transform-object-assign/):

> If you are authoring an application, rather than a library, it is recommended that you use the Object.assign polyfill instead.

I guess cozy-bar and cozy-client-js are more like libs, so using the plugin seems good to me. We could add this plugin to `babel-preset-cozy` and remove the polyfills, what do you think @CPatchane ?

I'm confused about `useBuiltIns` too. The official doc and [the one on the readme](https://github.com/babel/babel/tree/master/packages/babel-preset-env#usebuiltins) are not the same. rom what I understand:

- `useBuiltIns: false` : leave the `import "babel-polyfill"` statement alone. If there's no such statement, do nothing
- `useBuiltIns: entry` : used to be `useBuiltIns: true`, will replace `import "babel-polyfill"` by a list of imports for only the polyfills required by the env specified in the config. If there's no `import "babel-polyfill"`, do nothing
- `useBuiltIns: usage` : whenever a built in feature is used (such as `Object.assign` or `Promise`), add the required polyfill if the env needs it

So `usage` seems to be the way to go in the future, as it polyfills the things you use, and nothing more.
