### ISSUE TITLE
The two menus can be showed in the same time

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-bar#200]
If I concentrate and click quick enough on Apps and then on Settings menus, I can display both of them at the same time.

![capture d ecran 2018-05-09 a 12 10 36](https://user-images.githubusercontent.com/776764/39809495-3d466ba6-5382-11e8-8241-8deff0d44113.png)

**Comment by CPatchane** [comment]
Not relevant anymore since the v6 with the new navigation way
