### ISSUE TITLE
Can't disconnect on mobile browsers

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-bar#216]
The drawer menu needs a safe space so the user can click on the last item of the menu, the disconnect button in our case, especially on iPhone X but any mobile when minimal UI is triggered too.

On minimal UI, the Disconnect button is in the safe area therefore it's not clickable:

<img width="377" alt="screenshot 2018-08-06 14 20 29" src="https://user-images.githubusercontent.com/1280069/43716331-2068ea84-9984-11e8-8296-ba3472dcbb5a.png">

And when minimal UI is not triggered, the button is hidden underneath the Safari UI therefore it's not clickable either.

<img width="388" alt="screenshot 2018-08-06 14 20 07" src="https://user-images.githubusercontent.com/1280069/43716334-2368bd68-9984-11e8-9525-2772b5166860.png">

**Comment by ptbrowne** [comment]
> "Can't disconnect on minimal UI is trigger and on iPhone X"

I don't understand the title of the issue.

I don't understand the problem ? Is the drawer not scrollable ?
