### ISSUE TITLE
Layout breaks on Safari

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-bar#22]
Due to extra height to [role=application], it forces Safari to scroll the app content when we want full width & height with no scroll.

Screenshot:
![Safari scrolling bug](https://dl.dropboxusercontent.com/u/6801063/captures/safari.png)

I think the culprit here is the inherit on the height https://github.com/cozy/cozy-bar/blob/master/src/styles/base.css#L12

`body`'s height is 100vh, and we actually don't want that, we want the `[role=application]` to have a height of 100% of the remaining height which is 100vh minus the height of the cozy-bar.

**Comment by CPatchane** [comment]
@GoOz Is this bug still current?

**Comment by GoOz** [comment]
I don't think so, no.

**Comment by CPatchane** [comment]
@GoOz Thanks, so I close it.
