### ISSUE TITLE
Bar[Left | Center | Right] context

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-bar#241]
The cozy-bar exposes these components though the code located here : https://github.com/cozy/cozy-bar/blob/master/src/lib/api.js#L29

One problem we keep running into is that because the component is rendered in the cozy-bar, it also gets the context of the cozy-bar. Any HOC that relies on the context (like `connect` or `translate`) will use the wrong context and usually things break.

I don't know what the solution is, but if anyone has ideas, shoot!

____

Here's a small example of the problem:

```
const MyBreakingComponent = translate()(({ t }) => <div>{t('my_app_string')}</div>)

<Main>
  works: <MyBreakingComponent />
  doesn't work: <BarLeft><MyBreakingComponent /></BarLeft>
</Main>
```

In the second case, `t` comes from the cozy-var context, so it can provide the translations shipped with the bar, but not with the app.

**Comment by y-lohse** [comment]
One thing we could try is using portals, maybe? Something lik this might work:

```
const MyBreakingComponent = translate()(({ t }) => <div>{t('my_app_string')}</div>)

<Main>
  <BarLeft><div id="landing-zone" /></BarLeft>
  <Portal into="#landing-zone">
    <MyBreakingComponent />
  </Portal>
</Main>
```

**Comment by ptbrowne** [comment]
The portal gets the context because it is rendered in the same React as the other objects. But here, as you said earlier, we have problems because we are in another React root.

You could wrap your component in a new ContextProvider.

```
<BarLeft>
  <ContextProvider t={this.props.t}>
    <MyBreakingComponent>
  </ContextProvider> 
</BarLeft>
```

**Comment by y-lohse** [comment]
Duplicate of #144 , moving things over there.
