### ISSUE TITLE
BarCenter/BarLeft/BarRight api doesn't work with React

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-bar#297]
When using this api, we got a `<undefined></undefined>` as rendered component although we have correctly a React element in the `barCenter` variable [here](https://github.com/cozy/cozy-bar/blob/master/src/components/Bar.jsx#L166)

**Comment by ptbrowne** [comment]
Will be fixed by https://github.com/cozy/cozy-bar/pull/326

**Comment by CPatchane** [comment]
Fixed by #344 and many PRs before
