### ISSUE TITLE
Cozy Bar Title 🤔

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-bar#30]
After renaming Cozy Files to Cozy Drive, I see on the ['manifest.webapp'](https://github.com/cozy/cozy-drive/blob/master/manifest.webapp), the name have not Cozy word:

    "name": "Drive",

I change it to Cozy Drive but after this, when I start Cozy Drive app I see 'cozy cozy drive' on title.

I propose 2 changes:
- [ ] Remove the cozy word [here](https://github.com/cozy/cozy-bar/blob/cf3dbe758207e0a18535096a0de7e294b0bf6309/src/components/Bar.svelte#L9)
- [ ] Remove the lowercase [here](https://github.com/cozy/cozy-bar/blob/cf3dbe758207e0a18535096a0de7e294b0bf6309/src/styles/bar.css#L33)

What do you think ?

**Comment by y-lohse** [comment]
Strongly in favor.

**Comment by CPatchane** [comment]
Completely agree, I think we should specify when we want cozy before the app name. 👍

**Comment by kosssi** [comment]
@CPatchane Why would you like to specify that it is a cozy app?

I would prefer that we respect scrupulously the name of the application ;)

**Comment by CPatchane** [comment]
@kosssi In your case we will lost the way to put the 'cozy' name part in a bold text style, won't we?

**Comment by kosssi** [comment]
Yes, but why to have a specific experience to cozy app?

**Comment by GoOz** [comment]
I strongly disagree 😅 
If the "**cozy**" is in the mockup, it should stay that way. It's not our decision to make.
The question that remains, and that will be our decision to make, is how we show or not the word cozy. 
Another pending question is: what is the marketing name of Cozy apps? Cozy Drive? just Drive? To be more clear maybe, is the "cozy" prefix part of the name or just some kind of signature?

**Comment by gregorylegarec** [comment]
My points : 
* We must keep the Cozy branding : cozy in normal weight and second part of app's name in bold
* A Cozy app should be named "cozy <app suffix>" in `manifest.webapp`
* We got a card to manage this point : https://trello.com/c/zsq1dQq4/298-bar-11-e-36-etdeveloppeur-d-application-tiers-je-n-ai-pas-cozy-devant-le-nom-de-mon-app

What we plan to do :
Pass a flag to at Cozy-bar initialization to enable the "cozy prefix" in app title. If the flag is on, we will split the app name to be able to show `cozy` and `<app name>` in two different way.

Another option could be to add an  `editor` property in `manifest.webapp` and then display in the Cozy-bar `editor name` but I am not sure that is a better soution.

I am curions about @m4dz's opinion, if you read us don't hesitate to give your points.

**Comment by GoOz** [comment]
> Another option could be to add an editor property in manifest.webapp and then display in the Cozy-bar editor name but I am not sure that is a better soution.

I like this better than the split. 😄

**Comment by gregorylegarec** [comment]
Ping @pierrevdk @kelukelu

**Comment by pierrevdk** [comment]
The name of the app is "Cozy **Drive**" why a capital letter starting each word and the Drive in bold. 
I do agree as well that 3rd party apps should be called Cozy **Name of the 3rd party** but as greg said it is already planned.

**Comment by gregorylegarec** [comment]
@pierrevdk As I know for now, 3rd party apps will not have the __Cozy__ prefix.

**Comment by kosssi** [comment]
It's solve by https://github.com/cozy/cozy-bar/pull/37 🖖
